import React from 'react'
import styles from './Message.css';

export default () => (
    <div className={styles.Message}>
        This message box was lazy loaded. That means the JavaScript and CSS code used to
        display it are stored in a separate bundle, generated by webpack, which is loaded by the browser
        only after you clicked the button
    </div>
);
